import { Braces, Database, FileText, FolderGit2, Layers3, Terminal, X } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import type { NavIcon } from '../../types'
import { navigationItems } from '../../data/navigation'
import { projects } from '../../data/projects'

interface SidebarProps { isOpen: boolean; onClose: () => void }
const iconMap: Record<NavIcon, typeof FolderGit2> = { folder: FolderGit2, terminal: Terminal, braces: Braces, database: Database, layers: Layers3 }

export function Sidebar({ isOpen, onClose }: SidebarProps) {
  return <><>{isOpen && <button aria-label="Close navigation" className="fixed inset-0 z-40 bg-slate-900/20 lg:hidden" onClick={onClose} />}</><aside className={`fixed inset-y-0 left-0 z-50 flex w-[252px] flex-col border-r border-slate-200 bg-white pt-[68px] transition-transform duration-200 lg:sticky lg:top-0 lg:z-10 lg:h-[calc(100vh-68px)] lg:translate-x-0 lg:pt-0 ${isOpen ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 lg:hidden"><span className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Navigation</span><button aria-label="Close navigation" onClick={onClose} className="flex h-8 w-8 items-center justify-center rounded-md text-slate-400 hover:bg-slate-100"><X size={17} aria-hidden="true" /></button></div><div className="px-3 py-5"><p className="px-3 pb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-400">Knowledge base</p><nav className="space-y-1" aria-label="Primary navigation">{navigationItems.map((item) => { const Icon = iconMap[item.icon]; return <NavLink key={item.path} to={item.path} onClick={onClose} className={({ isActive }) => `group flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-colors ${isActive ? 'bg-slate-100 font-semibold text-slate-900' : 'text-slate-500 hover:bg-slate-50 hover:text-slate-800'}`}>{({ isActive }) => <><Icon size={17} strokeWidth={isActive ? 2.2 : 1.8} className={isActive ? 'text-[#2e5d94]' : 'text-slate-400 group-hover:text-slate-600'} aria-hidden="true" /><span className="flex-1">{item.label}</span>{item.label === 'Projects' && <span className={`font-mono text-[10px] ${isActive ? 'text-slate-500' : 'text-slate-400'}`}>{projects.length.toString().padStart(2, '0')}</span>}</>}</NavLink> })}</nav></div><div className="mt-auto border-t border-slate-100 px-6 py-5"><div className="flex items-start gap-2.5 text-slate-400"><FileText size={15} className="mt-0.5 shrink-0" aria-hidden="true" /><p className="text-xs leading-5">A quiet place to collect<br />what I want to remember.</p></div><p className="mt-5 font-mono text-[10px] text-slate-300">v0.1 · static knowledge base</p></div></aside></>
}
